### ISSUE TITLE
Url for the file not found

### ISSUE THREAD

**Issue by SilvaSeal** [Atreyagaurav/anime-helper-shell#10]
Sorry to bother, after the installation i was trying to download some anime, but the same "Url for the file not found" error appears.

`[silva@archlinux anime-helper-shell]$ ./ggshell.py 
Welcome, This is the CLI interactive for gogoanime.
Type help for more.
Ganime >>play one-piece 1
Getting Streaming Link: https://gogoanime.gg/one-piece-episode-1
Url for the file not found

Ganime >>download one-piece 1
Downloading: https://gogoanime.gg/one-piece-episode-1
Url for the file not found

Ganime >>exit
`

**Comment by Atreyagaurav** [comment]
Sorry about the late response, the `download`, `play` and `stream` as well as related functions are broken because gogoanime changed their internal. That keeps breaking regularly when they change stuffs, and I have to depend on others to fix that as I'm not that great with network part of the coding. 

Previously I had used a script from ani-cli to fix it but this time I couldn't do that the same way and haven't had time to analyse why. My bash skill isn't that great.

Hopefully someone will make a pull request, but since this doesn't have many users that hasn't happened.

You can still use other features, I mostly use it to keep track of anime I've watched and to check for new episodes and to binge without fillers. I use `web` command which opens the gogoanime page to actually watch the anime for now.

**Comment by Atreyagaurav** [comment]
Sorry it took so long, I'm not good with network problem at all. I've fixed it with a script made from ani-cli's script.
